### ISSUE TITLE
'via' field should not be mandatory if scope link is defined

### ISSUE THREAD

**Issue by LarsErikP** [zehweh/puppet-netplan#11]
netplan supports a configuration like this:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      match:
        macaddress: <foo>
      dhcp4: true
      routes:
        - to: 10.212.132.0/24
          scope: 'link'
          table: 1
```
This is not possible with this module, because the "via" field is mandatory. Really not sure what's the best way to fix it, but it should be possible to create a config like this
