### ISSUE TITLE
auth parameters not recognised

### ISSUE THREAD

**Issue by jamesps-ebi** [zehweh/puppet-netplan#23]
**'zehweh-netplan' version '1.0.0'
Puppet version 6.25.0
Ubuntu 20.04.3**

Not sure if this is a bug or my syntax is off, but I can't find an accurate example in the documentation for my use-case.

With the below puppet hiera data:
```
netplan::version: 2
netplan::renderer: NetworkManager
netplan::ethernets:
  TEST-WIRED:
    dhcp4: true
    match:
      name: eth*
    auth:
      key-management: 802.1x
      method: tls
      identity: "%{trusted.certname}"
      ca-certificate: /etc/ssl/certs/ca-certificates.crt
      client-certificate: "/etc/puppetlabs/puppet/ssl/certs/%{trusted.certname}.pem"
      client-key: "/etc/puppetlabs/puppet/ssl/private_keys/%{trusted.certname}.pem"
      client-key-password: "null"
netplan::wifis:
  TEST-WIFI:
    dhcp4: true
    match:
      name: wl*
    access-points:
      TEST1:
        auth:
          key-management: eap
          method: tls
          identity: "%{trusted.certname}"
          ca-certificate: /etc/ssl/certs/ca-certificates.crt
          client-certificate: "/etc/puppetlabs/puppet/ssl/certs/%{trusted.certname}.pem"
          client-key: "/etc/puppetlabs/puppet/ssl/private_keys/%{trusted.certname}.pem"
          client-key-password: "null"
netplan::config_file: '/etc/netplan/99-test-netplan.yaml'
```

I receive the following error when applying the catalogue:
```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Netplan::Ethernets[EBI-WIRED]:
parameter 'auth' unrecognized key 'key-management'
parameter 'auth' unrecognized key 'ca-certificate'
parameter 'auth' unrecognized key 'client-certificate'
parameter 'auth' unrecognized key 'client-key'
parameter 'auth' unrecognized key 'client-key-password' (file: /etc/puppetlabs/code/environments/jamesps_workstation_nac/modules/netplan/manifests/init.pp, line: 85) on node ubu20-n-495753433f.ebi.ac.uk
```

The same data structure works correctly when written directly to a file in `/etc/netplan/` and our test client is able to authenticate.
