### ISSUE TITLE
Unrecognized bond parameters

### ISSUE THREAD

**Issue by COOLBGT** [zehweh/puppet-netplan#32]
Hello. I am trying to use this module for an Ubuntu22 installation using 2 interfaces in bond. For the bond, I have the following in my server yaml
```
paramenters:
netplan::bonds:
    bond0:
      interfaces: [eth0, eth1]
      mtu: 9000
      parameters:
        mode: '802.3ad'
        mii-monitor-interval: '100'
        transmit-hash-policy: 'layer3+4'
        ad-select: 'count'
        lacp-rate: 'fast'
```

But out of all the parameters, only the **mode: '802.3ad'** is being recognized and applied to the netplan config properly. For the rest, I get the following error in the puppet run for the rest:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Netplan::Bonds[bond0]:
  parameter 'parameters' unrecognized key 'mii-monitor-interval'
  parameter 'parameters' unrecognized key 'transmit-hash-policy'
  parameter 'parameters' unrecognized key 'ad-select'
  parameter 'parameters' unrecognized key 'lacp-rate' (file: /etc/puppetlabs/code/environments/production/modules/netplan/manifests/init.pp, line: 136) on node host5.tbc.cloudsigma.com

```
I do see all those paramenters described in **templates/bonds.epp** of this module, but they do not seem to be recognized for some reason.

Am I doing something wrong declaring those parameters in my yaml?

As for my setup, I am using puppet7 with Foreman and version 2 of this module. The host server is an Ubuntu22 server installation

**Comment by DocFraggle** [comment]
@COOLBGT I ran into the same problem, you have to replace the dashes with underscores :)

```
netplan::bonds:
    bond0:
      interfaces: [eth0, eth1]
      mtu: 9000
      parameters:
        mode: '802.3ad'
        mii_monitor_interval: '100'
        transmit_hash_policy: 'layer3+4'
        ad_select: 'count'
        lacp_rate: 'fast'
```

See the manifest: https://github.com/zehweh/puppet-netplan/blob/master/manifests/bonds.pp#L308-L332
